# Generated by Django 5.0 on 2024-01-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_cart_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="coupon",
        ),
    ]
